name: Linting

on:
  push:
    branches: [main]
    paths:
      - cloudflare-worker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' #required for npm 8 or later.
      - run: (cd cloudflare-worker && npm install)
      - run: (cd cloudflare-worker && npm deploy)
        env:
          CI: true
